### ISSUE TITLE
Can't build on Armbian/Trixie

### ISSUE THREAD

**Issue by neben** [Seeed-Studio/seeed-linux-dtoverlays#141]
**Describe the bug**
Building fails on the latest official Armbian/Trixie install.

**To Reproduce**
1. Run `make all_rpi`

**Expected behavior**
Build completes without errors.

**Screenshots**
```
# make all_rpi
[...]
MODPOST Module.symvers
  CC [M]  lis331dlh-i2c.mod.o
  CC [M]  .module-common.o
  LD [M]  lis331dlh-i2c.ko
  BTF [M] lis331dlh-i2c.ko
  CC [M]  ltr30x.o
ltr30x.c: In function ‘ltr501_read_raw’:
ltr30x.c:642:31: error: implicit declaration of function ‘iio_device_claim_direct_mode’; did you mean ‘iio_device_claim_direct’? [-Wimplicit-function-declaration]
  642 |                         ret = iio_device_claim_direct_mode(indio_dev);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               iio_device_claim_direct
ltr30x.c:649:25: error: implicit declaration of function ‘iio_device_release_direct_mode’; did you mean ‘iio_device_release_direct’? [-Wimplicit-function-declaration]
  649 |                         iio_device_release_direct_mode(indio_dev);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         iio_device_release_direct
ltr30x.c: At top level:
ltr30x.c:1176:35: error: initialization of ‘int (*)(struct iio_dev *, const struct iio_chan_spec *, enum iio_event_type,  enum iio_event_direction,  bool)’ {aka ‘int (*)(struct iio_dev *, const struct iio_chan_spec *, enum iio_event_type,  enum iio_event_direction,  _Bool)’} from incompatible pointer type ‘int (*)(struct iio_dev *, const struct iio_chan_spec *, enum iio_event_type,  enum iio_event_direction,  int)’ [-Wincompatible-pointer-types]
 1176 |         .write_event_config     = &ltr501_write_event_config,
      |                                   ^
ltr30x.c:1176:35: note: (near initialization for ‘ltr501_info.write_event_config’)
ltr30x.c:1192:35: error: initialization of ‘int (*)(struct iio_dev *, const struct iio_chan_spec *, enum iio_event_type,  enum iio_event_direction,  bool)’ {aka ‘int (*)(struct iio_dev *, const struct iio_chan_spec *, enum iio_event_type,  enum iio_event_direction,  _Bool)’} from incompatible pointer type ‘int (*)(struct iio_dev *, const struct iio_chan_spec *, enum iio_event_type,  enum iio_event_direction,  int)’ [-Wincompatible-pointer-types]
 1192 |         .write_event_config     = &ltr501_write_event_config,
      |                                   ^
ltr30x.c:1192:35: note: (near initialization for ‘ltr301_info.write_event_config’)
make[3]: *** [/usr/src/linux-headers-6.18.10-current-bcm2711/scripts/Makefile.build:287: ltr30x.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.18.10-current-bcm2711/Makefile:2011: .] Error 2
make[1]: *** [Makefile:248: __sub-make] Error 2
make: *** [Makefile:157: all_rpi] Error 2
```

**Desktop (please complete the following information):**
 - OS: Armbian/Trixie

**Additional context**
reComputer 1024-10
```
$ uname -a
Linux localhost 6.18.10-current-bcm2711 #12 SMP PREEMPT Fri Feb 13 11:56:58 UTC 2026 aarch64 GNU/Linux
```

**Comment by neben** [comment]
This is caused by the `current` 6.18 kernel. Compilation works with the `legacy` 6.12 kernel. What is the status regarding support for the 6.18 kernel?

**Comment by Lesords** [comment]
Hello, we currently have no plans to support kernel 6.18.

If there are no other issues, you can use kernel version 6.12 for now.
