### ISSUE TITLE
ReTerminal-DM install fails

### ISSUE THREAD

**Issue by system24seven** [Seeed-Studio/seeed-linux-dtoverlays#72]
Followed https://wiki.seeedstudio.com/reterminal-dm-flash-OS/ to flash the ReTerminal-DM to raspbian 32 bit OS. 
When running the "sudo ./scripts/reTerminal.sh --device reTerminal-plus" command, a lot of modules seem to build, then the install fails at:

`depmod.....

DKMS: install completed.

Creating symlink /var/lib/dkms/ili9881d/0.1/source ->
                 /usr/src/ili9881d-0.1

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.10.17-v7l+ all KVERSION=5.10.17-v7l+....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.17-v7l+ (armv7l)
Consult /var/lib/dkms/ili9881d/0.1/build/make.log for more information.
Can't compile with this kernel, aborting
Please try to compile with the option --compat-kernel
DKMS make.log for ili9881d-0.1 for kernel 5.10.17-v7l+ (armv7l)
Tue  5 Sep 11:23:36 BST 2023
make -C /lib/modules/5.10.17-v7l+/build M=/var/lib/dkms/ili9881d/0.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.17-v7l+'
  CC [M]  /var/lib/dkms/ili9881d/0.1/build/ili9881d.o
/var/lib/dkms/ili9881d/0.1/build/ili9881d.c: In function ‘ili9881d_dsi_probe’:
/var/lib/dkms/ili9881d/0.1/build/ili9881d.c:501:12: error: ‘struct drm_panel’ has no member named ‘prepare_upstream_first’
  501 |  ctx->panel.prepare_upstream_first = true;
      |            ^
make[2]: *** [scripts/Makefile.build:279: /var/lib/dkms/ili9881d/0.1/build/ili9881d.o] Error 1
make[1]: *** [Makefile:1804: /var/lib/dkms/ili9881d/0.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.17-v7l+'
make: *** [Makefile:11: all] Error 2
`

I have tried the --compat-kernel, no change to the error log. 

uname - a:

Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

I have also tried this with the latest kernel (.103) and get same results. 
I am puropsely needing 32 bit kernel for software compatibility.

**Comment by system24seven** [comment]
turns out there is a minimum kernel version that is not displayed anywhere.

**Comment by system24seven** [comment]
Turns out that the minimum kernel version is not displayed anywhere.
